
package com.resetful.honeybot;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SingleLoginWSDelegate", targetNamespace = "http://SingleLoginAtIM/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SingleLoginWSDelegate {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userChecker", targetNamespace = "http://SingleLoginAtIM/", className = "com.resetful.honeybot.UserChecker")
    @ResponseWrapper(localName = "userCheckerResponse", targetNamespace = "http://SingleLoginAtIM/", className = "com.resetful.honeybot.UserCheckerResponse")
    public String userChecker(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tokenChecker", targetNamespace = "http://SingleLoginAtIM/", className = "com.resetful.honeybot.TokenChecker")
    @ResponseWrapper(localName = "tokenCheckerResponse", targetNamespace = "http://SingleLoginAtIM/", className = "com.resetful.honeybot.TokenCheckerResponse")
    public String tokenChecker(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
