
package com.resetful.honeybot;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SingleLoginWSService", targetNamespace = "http://SingleLoginAtIM/", wsdlLocation = "http://xiaozhi.189.cn:8082/SingleLoginInInterface/SingleLoginWSPort?wsdl")
public class SingleLoginWSService
    extends Service
{

    private final static URL SINGLELOGINWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SINGLELOGINWSSERVICE_EXCEPTION;
    private final static QName SINGLELOGINWSSERVICE_QNAME = new QName("http://SingleLoginAtIM/", "SingleLoginWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://xiaozhi.189.cn:8082/SingleLoginInInterface/SingleLoginWSPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SINGLELOGINWSSERVICE_WSDL_LOCATION = url;
        SINGLELOGINWSSERVICE_EXCEPTION = e;
    }

    public SingleLoginWSService() {
        super(__getWsdlLocation(), SINGLELOGINWSSERVICE_QNAME);
    }

    public SingleLoginWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SINGLELOGINWSSERVICE_QNAME, features);
    }

    public SingleLoginWSService(URL wsdlLocation) {
        super(wsdlLocation, SINGLELOGINWSSERVICE_QNAME);
    }

    public SingleLoginWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SINGLELOGINWSSERVICE_QNAME, features);
    }

    public SingleLoginWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SingleLoginWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SingleLoginWSDelegate
     */
    @WebEndpoint(name = "SingleLoginWSPort")
    public SingleLoginWSDelegate getSingleLoginWSPort() {
        return super.getPort(new QName("http://SingleLoginAtIM/", "SingleLoginWSPort"), SingleLoginWSDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SingleLoginWSDelegate
     */
    @WebEndpoint(name = "SingleLoginWSPort")
    public SingleLoginWSDelegate getSingleLoginWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SingleLoginAtIM/", "SingleLoginWSPort"), SingleLoginWSDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SINGLELOGINWSSERVICE_EXCEPTION!= null) {
            throw SINGLELOGINWSSERVICE_EXCEPTION;
        }
        return SINGLELOGINWSSERVICE_WSDL_LOCATION;
    }

}
